Repository googleapis/python-cloud-core, pull requests merged in 2020-10, with the labels that each got.

#37 chore: release v1.4.2
  setup.py
Labels: autorelease: pending, cla: yes

#40 fix: avoid using 'pkg_resources' to determine version
  google/cloud/_http.py
  google/cloud/version.py
  setup.py
Labels: cla: yes

#22 chore: add snippet-bot, secrets manager to CI (via synth)
  .github/snippet-bot.yml
  .kokoro/build.sh
  .kokoro/populate-secrets.sh
  .kokoro/release/common.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/trampoline.sh
  CONTRIBUTING.rst
  docs/conf.py
  scripts/decrypt-secrets.sh
  synth.metadata
Labels: cla: yes, context: full

#43 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full
