Repository googleapis/python-cloud-core, pull requests merged in 2020-08, with the labels that each got.

#17 feat: add support for Python 3.8
  noxfile.py
  setup.py
Labels: cla: yes, type: process

#15 feat: add quota_project, credentials file, and scopes options
  google/cloud/client.py
  tests/unit/test_client.py
Labels: cla: yes

#14 docs: update docs build (via synth)
  .gitignore
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  docs/conf.py
  noxfile.py
  synth.metadata
Labels: cla: yes, context: full

#24 fix(deps): fix missing attributes in client_options
  setup.py
Labels: cla: yes
