Repository googleapis/python-cloud-core, pull requests merged in 2020-12, with the labels that each got.

#50 chore: add config / docs for 'pre-commit' support
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  synth.metadata
Labels: automerge, cla: yes, context: partial

#55 feat: add support for Python 3.9, drop support for Python 3.5
  CONTRIBUTING.rst
  README.rst
  noxfile.py
  setup.py
  testing/constraints-3.9.txt
Labels: cla: yes

#57 chore: tweak 'python_requires' to match supported Python versions
  setup.py
Labels: cla: yes

#63 chore: update supported py versions in CONTRIBUTING and update precommit version
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  synth.metadata
Labels: cla: yes, context: partial

#65 docs(python): document adding Python 3.9 support, dropping 3.5 support
  CONTRIBUTING.rst
  synth.metadata
Labels: cla: yes, context: full
