Repository googleapis/python-cloud-core, pull requests merged in 2021-05, with the labels that each got.

#91 chore: update contributors doc (via synth)
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  synth.metadata
Labels: automerge, cla: yes, context: full

#93 chore: add library type to .repo-metadata.json
  .repo-metadata.json
Labels: cla: yes

#95 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
Labels: automerge, cla: yes
