Repository googleapis/python-cloud-core, pull requests merged in 2021-01, with the labels that each got.

#67 chore: add constraints file
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.6.txt
Labels: cla: yes

#68 chore: use 'http' URL in Apache license
  LICENSE
  docs/_static/custom.css
  synth.metadata
Labels: cla: yes, context: full

#71 chore: tweak kokoro setup (via synth)
  .kokoro/build.sh
  .kokoro/docs/docs-presubmit.cfg
  .trampolinerc
  synth.metadata
Labels: cla: yes, context: full

#51 feat: infer project from explicit service account creds
  google/cloud/client.py
  tests/unit/test_client.py
Labels: cla: yes

#72 build(python): make `NOX_SESSION` optional
  .trampolinerc
  synth.metadata
Labels: cla: yes, context: full

#74 chore: Add header checker config to python library synth
  .github/header-checker-lint.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#76 build: migrate to flakybot
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
Labels: cla: yes
