Repository googleapis/python-cloud-core, pull requests merged in 2021-04, with the labels that each got.

#87 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: cla: yes, context: full, samples

#89 chore: prevent normalization of semver versioning
  setup.py
Labels: cla: yes

#88 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: automerge, cla: yes, context: full

#90 chore(revert): revert preventing normalization
  setup.py
Labels: automerge, cla: yes
